### ISSUE TITLE
build issue with i586-mingw32msvc-g++ 4.2.1

### ISSUE THREAD

**Issue by pphaneuf** [quadra-game/quadra#132]
```
../quadra/source/res.h: In copy constructor 'Res_mem::Res_mem(const Res_mem&)':
../quadra/source/res.h:62: error: 'Res::Res(const Res&)' is private
../quadra/source/res.h:66: error: within this context
../quadra/source/res.h: In copy constructor 'Res_doze::Res_doze(const Res_doze&)':
../quadra/source/res.h:103: note: synthesized method 'Res_mem::Res_mem(const Res_mem&)' first required here 
../quadra/source/quadra.cc: In function 'void<unnamed>::init_stuff(bool, bool)':
../quadra/source/quadra.cc:247: note: synthesized method 'Res_doze::Res_doze(const Res_doze&)' first required here 
make: *** [source/quadra.o] Error 1
```

From what I can tell, the compiler is refusing to take a `const Res&` to a `Res_doze` (which derives from Res, indirectly). This should be trivial, but doesn't work for some reason?

This works with GCC 4.6.3 and Clang 3.4 (as provided in Xcode 5.1.1).

**Comment by pphaneuf** [comment]
According to [this Stack Overflow post](http://stackoverflow.com/questions/1826934/copy-constructor-needed-with-temp-object), it's sort of a bug in the pre-C++11 standard, where many compilers were accepting non-compliant code, but the standard was being silly, so the C++11 standard was matched to follow the compilers... but some compilers (like GCC 4.2.1) might enforce the earlier standard. :stuck_out_tongue:

There's also no newer version of `mingw32` packaged on Ubuntu (or Debian), but it seems that there's a fork called `mingw-w64` that's a bit more lively (4.6.3 on Ubuntu precise, 4.8.2 on trusty). Despite the name, it supports both 32-bit and 64-bit, just get the `g++-mingw-w64-i686` package.
